### PR TITLE
NFT update, burn and get all NFT listings for a profile

### PR DESCRIPTION
**Pull request by ankushKun**
I will now use this to burn all ColoredPixels 🔥

### CODE REVIEW

**Comment by ItsAditya-xyz** [comment]
GetNFT() is already a thing on deso.py
Rest all okay.

**Comment by ankushKun** [comment]
But I added `getAllNFTs()`, didn't touch `GetNFT()` 💀

**Comment by ItsAditya-xyz** [comment]
Bruh. Both works the same. See the endpoint.

**Comment by ankushKun** [comment]
@AdityaChaudhary0005 
`getNFT()` is `get-nft-entries-for-nft-post`
`getAllNFTs()` is `get-nfts-for-user`
🤔

**Comment by kennyjacobson** [comment]
I already did `get-nfts-for-user`. It's the last method on the old `Users.py`, it's called `getNFTs`. 
 
 You already converted it in your first PR, you renamed it `get_nfts` (on `users.py`)

**Comment by ankushKun** [comment]
Oh, It is inside Users.py 👍 
Removed the duplicate
@AdityaChaudhary0005

**Comment by ItsAditya-xyz** [comment]
Thanks. I am merging this now. Will deploy new release in a day or 2

**Pull request merged**
