### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EpicCodeWizard**
For me, getting my seed hex and public key credentials from BitClout's console was very hard. I saw that many users had the same issue, so I created a website which contains steps to retrieve it. The steps are really simple and I've updated the README with it. Please merge it to master and update as needed. Note: The user's credentials are copied to their clipboard in the format of `publicKey="xxxxx", seedHex="xxxxxx"`.

### CODE REVIEW

**Comment by ItsAditya-xyz** [comment]
Are you saying that a web app can access deso seedHex? You should instead go and apply for bug bounty.

Talking of the problem, i agree it's not that straight to get the credentials from console. And to fix that I am thinking of having a `getSeedHexFromMnemonic()` function using which you can generate seedHex from seed phrase. 

PS. can't access the repl URL. Error: `The repl didn't wake up in time. Please try again in 30 seconds.`

Edit: Saw the video. Looks like bookmarklet thing that runs script in identity window. Don't think it's a good idea to encourage anyone to use this method imo. How can one be even sure that it's only running a simple copy/paste script and not a POST request to a server taking away the credentials? `getSeedHexFromMnemonic()` would be better as it will work offline!

**Comment by EpicCodeWizard** [comment]
No, I didn't mean a web app can access Deso seedHex. I just made a script to get the seedHex from a person's portal (by reading localStorage) and alert it to them. As for replit, there was an outage, so my demo isn't working.

**Comment by ItsAditya-xyz** [comment]
> As for replit, there was an outage, so my demo isn't working.

Oh that makes sense.

I edited my original comment with more thoughts on it

**Comment by EpicCodeWizard** [comment]
I personally wasted a lot of time figuring out my seedHex so I wanted others to have it automated (I was using Deso for a hackathon project). I completely understand the risks with bookmarklets.

P.S. I absolutely love the library, are there any open issues or features I can help with?

**Comment by ItsAditya-xyz** [comment]
Thank you for your efforts to make it better :) I understand that finding credential isn't easy. I too wasted a lot of time initially.
Maybe you can add more endpoints in library? I guess the library is missing some DAO endpoints. Maybe improve docs. Add comments in every function so that it shows in VS code editor help recommendation.

**Comment by EpicCodeWizard** [comment]
> Thank you for your efforts to make it better :) I understand that finding credential isn't easy. I too wasted a lot of time initially. Maybe you can add more endpoints in library? I guess the library is missing some DAO endpoints. Maybe improve docs. Add comments in every function so that it shows in VS code editor help recommendation.

Sure. I'll transfer the docs to something like `readthedocs` and make a coming soon section, along with a discord server. Also, can I get your discord username?

**Comment by ItsAditya-xyz** [comment]
oh, discord server would get too much. instead we can use the official discord of deso (I am moderator there)
ADITYA#3780

**Pull request closed without merging**
