### PR TITLE
added clarifications and a little configurability

### PR DESCRIPTION
**Pull request by melzubeir**
on getFollowsStateless() following/follower and setting nodeURL

### CODE REVIEW

**Comment by melzubeir** [comment]
the commit notes should be self-explanatory

**Comment by ItsAditya-xyz** [comment]
Great work ser

**Comment by ItsAditya-xyz** [comment]
Have forced pushed it and fixed later on but just in case yo don't know, this self.readerPublicKey will be undefined in function parameter

image

**Comment by melzubeir** [comment]
my bad, won't happen again

**Pull request merged**
